### ISSUE TITLE
The Best Obsidian Theme!

### ISSUE THREAD

**Issue by mrkuramoto** [kartik-karz/subtlegold-obsidian#1]
Thank you very much for this Theme. I have tested most of them and this is the best one.
- fonts are very pleasant;
- space between line perfect!
- Preview and Edit mode have the same font (😃😃😃😃😃)
- and in general, the appearance is smooth!

Sorry to have written in "issues" but I haven't found another place to write.

**Comment by kartik-karz** [comment]
Thanks a lot @mrkuramoto. It's good to hear that people like my theme! 😄 
Also thanks for reminding me about making a post on the forum, I had forgotten about it but thanks to your reminder here it is now.
[Post to the theme](https://forum.obsidian.md/t/theme-subtlegold-theme/5572)
