### ISSUE TITLE
Hard to read file names when hovering (dark theme)

### ISSUE THREAD

**Issue by aroberge** [kartik-karz/subtlegold-obsidian#2]
I really like the simplicity and look of your theme; well done!

There is just one minor annoyance: when hovering over file names (dark mode), the contrast makes it near impossible to read the filename with the dark text and the dark gray background.
![image](https://user-images.githubusercontent.com/629698/93523319-42dca600-f909-11ea-86c5-3024157faf8a.png)

I would suggest that the text should possibly be the default "subtle gold" color in this case.   If you don't plan on changing it, and if you know off-hand which settings it might be, I would appreciate if you could give me a pointer so that I could change it locally.

Thank you for your good work.

**Comment by aroberge** [comment]
Changing line 172 to 
```css
  color: var(--golden-brown);
```
![image](https://user-images.githubusercontent.com/629698/93540575-7976e880-f92a-11ea-95dc-ecfbc0215e30.png)

I don't know if this is the best choice, but I find it to be better.

**Comment by kartik-karz** [comment]
Thanks a lot @aroberge I have fixed it now. The change should be propagated to the theme store within 12 hours.
